// Generated by CoffeeScript 1.4.0
(function() {
  var CssZapette, cssZapette,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  CssZapette = (function() {

    function CssZapette() {
      this.playPause = __bind(this.playPause, this);

      this.bindKey = __bind(this.bindKey, this);
      this.initialize();
    }

    CssZapette.prototype.initialize = function() {
      var body;
      document.addEventListener('keyup', this.bindKey, false);
      body = document.getElementsByTagName('body')[0];
      return this.items = body.getElementsByTagName('*');
    };

    CssZapette.prototype.bindKey = function(evt) {
      evt.preventDefault();
      if (evt.keyCode === 13) {
        return this.playPause();
      }
    };

    CssZapette.prototype.playPause = function() {
      var i, item, style, _ref;
      for (i in this.items) {
        item = this.items[i];
        if (((_ref = this.items[i].style) != null ? _ref.webkitAnimationPlayState : void 0) != null) {
          style = this.items[i].style;
          if (style.webkitAnimationPlayState === 'paused') {
            style.webkitAnimationPlayState = 'running';
          } else {
            style.webkitAnimationPlayState = 'paused';
          }
        }
      }
    };

    return CssZapette;

  })();

  window.CssZapette = CssZapette;

  cssZapette = new CssZapette;

}).call(this);
